# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/Nexys4DDR_C.xdc

# IP: ip/Square_Root/Square_Root.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Square_Root || ORIG_REF_NAME==Square_Root} -quiet] -quiet

# IP: ip/ClkGen/ClkGen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ClkGen || ORIG_REF_NAME==ClkGen} -quiet] -quiet

# XDC: ip/ClkGen/ClkGen_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ClkGen || ORIG_REF_NAME==ClkGen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ClkGen/ClkGen.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ClkGen || ORIG_REF_NAME==ClkGen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ClkGen/ClkGen_ooc.xdc
